// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace libmapgen
{
	public class DummyPass : IMapPass
	{
		public DummyPass () { }

		public void call(MapArea map) { }

		public string name () { return "Dummy Pass"; }
	}
}

