// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace libmapgen
{
	[TestFixture()]
	public class RandomGeneratorTest
	{
		[Test()]
		public void GenerationTest ()
		{
			for (var i=0; i<5; i++) {
				Assert.GreaterOrEqual(RandomGenerator.generate (0, 1), 0);
				Assert.Less (RandomGenerator.generate (0, 1), 1);

				Assert.GreaterOrEqual (RandomGenerator.generate (45, 60), 45);
				Assert.Less (RandomGenerator.generate (0, 60), 60);
			}
		}
	}
}

