// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace libmapgen
{
	public class Ruleset
	{
		public IInitialMapGenerator generator;
		public List<IMapPass> passes;

		public Ruleset ()
		{
		}

		public MapArea generate()
		{
			MapArea map = generator.generate ();
			foreach (var pass in passes)
			{
				pass.call (map);
			}
			return map;
		}
	}
}

