// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace libmapgen
{
	public class Tile
	{
		public int id;
		public string name;
		public float frequency;

		public Tile (int id, string name, float frequency)
		{
			this.id = id;
			this.name = name;
			this.frequency = frequency;
		}
	}
}